### PR TITLE
FM2-525: Customize IG homePage

### PR DESCRIPTION
**Pull request by abertnamanya**
Ticket link: https://issues.openmrs.org/browse/FM2-525

Screenshot from 2022-11-29 19-19-35

Screenshot from 2022-11-29 19-19-37

### CODE REVIEW

**Comment by abertnamanya** [comment]
Dear @mozzy11 please help with merging this PR we are time bad, we are drafting a report for GSOD

**Comment by mozzy11** [comment]
Thanks @abertnamanya

**Comment by abertnamanya** [comment]
Thank you  @mozzy11

**Comment by sherrif10** [comment]
Thanks @abertnamanya @mozzy11

**Pull request merged**
